# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='renting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=25)),
                ('starttime', models.CharField(max_length=6)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conveyance.cities')),
            ],
        ),
        migrations.CreateModel(
            name='vehicles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vname', models.CharField(max_length=100)),
                ('hours', models.IntegerField(default=12)),
                ('count', models.IntegerField(default=10)),
                ('costperkm', models.CharField(max_length=6)),
                ('img', models.CharField(default='/static/conveyance/images/x8.jpg', max_length=3000)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conveyance.cities')),
            ],
        ),
    ]
