# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-22 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conveyance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renting',
            name='city',
        ),
        migrations.AddField(
            model_name='renting',
            name='vehicle_name',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
    ]
