# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=12)),
                ('start_date', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='cityinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attractions', models.CharField(max_length=500)),
                ('guide', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='pcks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=200)),
                ('places', models.CharField(max_length=250)),
                ('price', models.CharField(max_length=10)),
                ('duration', models.CharField(max_length=10)),
                ('img', models.CharField(max_length=3000)),
                ('i1', models.CharField(default='/static/packages/images/a1.jpg', max_length=2000)),
                ('i2', models.CharField(default='/static/packages/images/a1.jpg', max_length=2000)),
                ('i3', models.CharField(default='/static/packages/images/a1.jpg', max_length=2000)),
                ('i4', models.CharField(default='/static/packages/images/a1.jpg', max_length=2000)),
            ],
        ),
        migrations.AddField(
            model_name='cityinfo',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.pcks'),
        ),
    ]
