# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 20:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='p',
            new_name='package_name',
        ),
    ]
