# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accommodation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hname', models.CharField(max_length=100)),
                ('single', models.CharField(max_length=5)),
                ('double', models.CharField(max_length=5)),
                ('family', models.CharField(max_length=5)),
                ('multiple', models.CharField(max_length=5)),
                ('sno', models.IntegerField(default=5)),
                ('dno', models.IntegerField(default=5)),
                ('fno', models.IntegerField(default=5)),
                ('mno', models.IntegerField(default=5)),
                ('img1', models.CharField(default='/static/hotels/images/20-seater.jpg', max_length=2000)),
                ('img2', models.CharField(default='/static/hotels/images/20-seater.jpg', max_length=2000)),
                ('img3', models.CharField(default='/static/hotels/images/20-seater.jpg', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='hbookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=12)),
                ('Checkin', models.CharField(max_length=15)),
                ('Checkout', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=25)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.cities')),
                ('hotel_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.accommodation')),
            ],
        ),
        migrations.AddField(
            model_name='accommodation',
            name='cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.cities'),
        ),
    ]
