# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hbookings',
            name='bookincost',
            field=models.IntegerField(default=1500),
        ),
        migrations.AddField(
            model_name='hbookings',
            name='bookintype',
            field=models.CharField(default='single bed', max_length=100),
            preserve_default=False,
        ),
    ]
