# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_auto_20171121_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hbookings',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hbookings',
            name='hotel_name',
            field=models.CharField(max_length=100),
        ),
    ]
